# Generated by Django 5.1.2 on 2024-10-25 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversion',
            name='direction',
            field=models.CharField(choices=[('FROM_UZS', "So'mdan"), ('TO_UZS', "So'mga")], default='TO_UZS', max_length=255),
            preserve_default=False,
        ),
    ]
