# Generated by Django 5.1.2 on 2024-10-25 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversion', '0002_conversion_direction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversion',
            name='convert_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
