# Generated by Django 5.1.2 on 2024-10-22 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversion', '0003_alter_conversion_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversion',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='conversion',
            name='convert_sum',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
