# Generated by Django 5.1.2 on 2024-10-23 05:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversion', '0004_alter_conversion_amount_alter_conversion_convert_sum'),
        ('currency', '0004_remove_currency_rate'),
        ('user', '0005_alter_user_chat_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversion',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='currency.currency'),
        ),
        migrations.AlterField(
            model_name='conversion',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user'),
        ),
    ]
