
from datetime import time


#STATES
ASK_NAME="ASK_NAME"
ASK_PHONE="ASK_PHONE"
ASK_CURRENCY="ASK_CURRENCY"
POST_MESSAGE="📤 Post yuborish"

SELECT_ACTION="SELECT_ACTION"
ENTER_AMOUNT="ENTER_AMOUNT"

BACK="Orqaga qaytish↩️"

UZBEK_PHONE_REGEX = r"^(\+998|998)[0-9]{9}$"

SHOW_OTHER_CURRENCIES="💸Boshqa valyutalar"
SHOW="SHOW"
SELL="Sotish💵"

BUY="Sotib olish💰"
UZS="🇺🇿So'm"
USD = "🇺🇸Dollar"
RUB = "🇷🇺Rubl"
EUR = "🇪🇺Yevro"

SUM="So'm"


ADMIN_USERNAME = 'admin'
ADMIN_PASSWORD = '1'

ASK_LOGIN="ASK_LOGIN"
ASK_PASSWORD="ASK_PASSWORD"
ADMIN_MENU="ADMIN_MENU"
REFERRAL_MENU="🔖 Referral"

ASK_ADMIN_LOGIN="ASK_ADMIN_LOGIN"
ASK_ADMIN_PASSWORD="ASK_ADMIN_PASSWORD"
ADMIN_MENU_STATE="ADMIN_MENU_STATE"
POST_CONFIRMATION="POST_CONFIRMATION"
DELETE_REFERRAL_STATE="🗑 Referralni o`chirish"
CREATE_REFERRAL_STATE="➕ Referral qo'shish"
VIEW_REFERRALS="🔗 Referralni ko'rish"
REFERRAL_OPTIONS="REFERRAL_OPTIONS"

BOT_STATS="📊 Bot statistikasi"
USER_STATS="👥 Foydalanuvchilar statistikasi"
START="🏠 Bosh menyuga"


REFERRAL_CREATE_NAME = "REFERRAL_CREATE_NAME"

SELECT_CURRENCY = "SELECT_CURRENCY"



DAILY_TIME_HOUR=15
DAILY_TIME_MINUTE=14