# Generated by Django 5.1.2 on 2024-10-21 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('currency_code', models.CharField(max_length=8)),
                ('rate', models.BigIntegerField()),
            ],
        ),
    ]
