# Generated by Django 5.1.2 on 2024-10-22 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0002_alter_currency_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='cb_price',
            field=models.DecimalField(decimal_places=2, default=1000, max_digits=10),
            preserve_default=False,
        ),
    ]
