# Generated by Django 5.1.2 on 2024-10-23 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0003_currency_cb_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currency',
            name='rate',
        ),
    ]
