# Generated by Django 5.1.2 on 2024-10-21 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('name', models.BigIntegerField(db_index=True, primary_key=True, serialize=False)),
                ('phone_number', models.CharField(max_length=64)),
            ],
        ),
    ]
