# Generated by Django 5.1.2 on 2024-10-21 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_registered_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(db_index=True, max_length=64, primary_key=True, serialize=False),
        ),
    ]
