# Generated by Django 5.1.2 on 2024-10-25 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_change_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default=1, max_length=64),
            preserve_default=False,
        ),
    ]
