# Generated by Django 5.1.2 on 2024-10-25 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='main_currency',
            new_name='favourite_currency',
        ),
    ]
