# Generated by Django 5.1.2 on 2024-10-23 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_user_chat_id_alter_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='chat_id',
            field=models.CharField(max_length=64, primary_key=True, serialize=False),
        ),
    ]
